language: node_js
# as we're not running unittests, force success return status
script: "/bin/true"
# always want to know when we've had a failed build, or if the status has changed (i.e. a failed build is now passing)
# TODO ensure that this only emails exec!
notifications:
  on_success: change
  on_failure: always
  email:
    - jamie@jamietanna.co.uk
    - harrymt@me.com
# currently deploying to Jamie Tanna's heroku account
# references:
# - http://blog.travis-ci.com/2013-07-09-introducing-continuous-deployment-to-heroku/
# - http://docs.travis-ci.com/user/deployment/heroku/#Application-to-deploy
deploy:
  provider: heroku
  buildpack: https://github.com/ddollar/heroku-buildpack-multi
  api_key:
    secure: lI2dH1pSw7D4WBXfFLVgvmZaZLS+TXawZQfRSWqqZvR4LT/ScSvkX3hcBcbPqos4pt6Alrvx2ebqWESih3m0u/SuKQhO3DNn8ZyRyqxCG4QhcEjTftiBZdDMMAAfFwxrrdbsPv6hwFJ1rPsgE4JubU0ih3oYwkPnatgVvDYGrKWIqfpq5U/gEMHlso3Js07ElAY06C6CzR5MEss8W+sA+8IF+7RazNumdvsS0/daGAjN9T6GM+tiMtbklamELygtS/D8VmwFoxcF5I/8bEJtYTNk5YggjlwIoqZzNdIzrcePLia4Q1aS+h0IOvTab8uLZIVMyI37B/ujbNqgUeNkKXYSsGYvKDMMjX1r0IeF5r/57k31rDK4dcg72ezxdE41NDj3w2GjHAElBTdSmiqAZp23Cyp0BgEGxxYnBRLLtPXF+epSHvgNNgPKZK7+n93fwuaUwtcXCso9dXpN25rLouVXWT4Z/gqpGj4vBMrx4df3blDB6ZFfVXJUeyewGmn7/oo4upvysHUXwzUZw62Bux02Rnk2qa1pKA0qgIFVUA/F6yCueqzEwgErOp40WSAcVuKV0KcydFi6V8MMJLWRa4fssPSkJi8pEoD/WT6ywBnP06XVM9QK0vYZ7kcVqoZnlltdi6HsQco6ff9hHTZJXSg4cC2V3CTYTvD3eXhYuoY=
  app:
    # we want a staging and a production site - so we can check changes before they go live
    master: hacknotts-staging
    prod: hacknotts-prod

before_install:
  - gem install sass
  - npm install
  - grunt
